src/enterprise_system/urls.py
from django.contrib import admin
from django.urls import path, include
from django.conf.urls.static import static
from django.conf import settings

from si_system.views import index


urlpatterns = [
    path("devices/", include("si_devices.urls", namespace="si_devices")),
    path("tests/", include("si_tests.urls", namespace="si_tests")),
    path("admin/", admin.site.urls),
    path("users/", include("si_users.urls", namespace="si_users")),
    path("", index, name="index"),
]

# Запуск медиафайлов локально
if settings.DEBUG:
    urlpatterns += static(settings.MEDIA_URL, document_root=settings.MEDIA_ROOT)

src/si_devices/urls.py
from django.urls import path
from django.conf import settings
from django.conf.urls.static import static

from si_devices import views


app_name = 'si_devices'


urlpatterns = [
    path("versions/success/<int:pk>", views.SuccessVersionView.as_view(), name="version-success"),
    path("versions/edit/<int:pk>", views.VersionEditView.as_view(), name="version-edit"),
    path("versions/create", views.VersionCreateView.as_view(), name="version-create"),
    path("versions", views.VersionListView.as_view(), name="version-list"),
    path("<int:pk>/update", views.device_update, name="device-update"),
    path("create", views.DeviceCreateView.as_view(), name="device-create"),
    path("<int:pk>", views.DeviceDetailView.as_view(), name="device-detail"),
    path("", views.DeviceListView.as_view(), name="device-list"),
]


if settings.DEBUG:
    urlpatterns += static(settings.MEDIA_URL, document_root=settings.MEDIA_ROOT)

src/si_system/urls.py
from django.urls import include, path



app_name = "si_system"

src/si_tests/urls.py
from django.urls import path
from django.conf import settings
from django.conf.urls.static import static

from si_tests import views


app_name = "si_tests"


urlpatterns = [
    path("<int:pk>/update", views.TestUpdateView.as_view(), name="test-update"),
    path("create", views.TestCreateView.as_view(), name="test-create"),
    path("<int:pk>", views.DetailView.as_view(), name="test-detail"),
    path("", views.TestListView.as_view(), name="test-list"),
]


if settings.DEBUG:
    urlpatterns += static(settings.MEDIA_URL, document_root=settings.MEDIA_ROOT)

src/si_users/urls.py
from django.urls import path

from si_users.views import login, registration, profile, logout

app_name = "si_users"

urlpatterns = [
    path("login/", login, name="login"),
    path("registration/", registration, name="registration"),
    path("profile/", profile, name="profile"),
    path("logout/", logout, name="logout"),
]

src/si_system/models.py
from django.db import models

# Create your models here.

src/si_system/views.py
from django.shortcuts import render


def index(request):
    return render(request, "si_system/index.html")

src/si_system/templates/si_system/base.html
{% load static %}

<!doctype html>
<html lang="ru">
<head>
    <!-- Required meta tags -->
    <meta charset="utf-8">
    <meta name="viewport" content="width=device-width, initial-scale=1, shrink-to-fit=no">

    <meta name="description" content="">
    <meta name="author" content="">

    {% block title %} {% endblock %}

    <!-- Bootstrap CSS -->
    <link rel="stylesheet" 
          href="https://maxcdn.bootstrapcdn.com/bootstrap/4.0.0/css/bootstrap.min.css"
          integrity="sha384-Gn5384xqQ1aoWXA+058RXPxPg6fy4IWvTNh0E263XmFcJlSAwiGgFAW/dAiS6JXm" 
          crossorigin="anonymous">

    {% block css %}
        <link rel="stylesheet" href="{% static 'css/style.css' %}">
    {% endblock %}
{#    HTMX   #}
{#    <script src="{% static 'js/htmx.min.js' %}" defer></script>#}


    {# Load the tag library #}
    {% load bootstrap4 %}

    {# Load CSS and JavaScript #}
    {% bootstrap_css %}
    {% bootstrap_javascript %}

    {# Display django.contrib.messages as Bootstrap alerts #}
    {% bootstrap_messages %}

</head>

<body hx-headers='{"X-CSRFToken": "{{ csrf_token }}"}'>
{#block nav#}
{% block nav %}
    {#  <nav class="navbar navbar-expand-lg navbar-light bg-light">#}
    <nav class="navbar navbar-expand-lg navbar-dark bg-dark ">
        <a class="navbar-brand" href="#">Noguzadericshenskiy</a>
        {% if user.is_authenticated %}

            <button class="navbar-toggler" type="button" data-toggle="collapse" data-target="#navbarSupportedContent"
                    aria-controls="navbarSupportedContent" aria-expanded="false" aria-label="Toggle navigation">
                <span class="navbar-toggler-icon"></span>
            </button>

            <div class="collapse navbar-collapse" id="navbarSupportedContent">
                <ul class="navbar-nav mr-auto">
                    <li class="nav-item active">
                        <a class="nav-link" href="{% url "index" %}">Home<span class="sr-only">(current)</span></a>
                    </li>

                    <li class="nav-item dropdown">
                        <a class="nav-link dropdown-toggle" href="#" id="navbarDevice" role="button"
                           data-toggle="dropdown"
                           aria-haspopup="true" aria-expanded="false">
                            Изделия
                        </a>

                        <div class="dropdown-menu" aria-labelledby="navbarDropdown">
                            <a class="dropdown-item" href="{% url "si_devices:device-list" %}">Список изделий</a>
                            <a class="dropdown-item" href="{% url "si_devices:device-create" %}">Добавить изделие</a>
                            <a class="dropdown-item" href="#">Редактировать изделие</a>
                            <a class="dropdown-item" href="#">Удалить изделие</a>
                            <div class="dropdown-divider"></div>
                            <a class="dropdown-item" href="{% url "si_devices:version-create" %}">Добавить версию</a>
                            <a class="dropdown-item" href="#">Редактировать версию</a>
                            <a class="dropdown-item" href="{% url "si_devices:version-list" %}">Список версий</a>
                        </div>
                    </li>

                    <li class="nav-item dropdown">
                        <a class="nav-link dropdown-toggle" href="#" id="navbarCheck" role="button"
                           data-toggle="dropdown"
                           aria-haspopup="true" aria-expanded="false">
                            Испытания
                        </a>

                        <div class="dropdown-menu" aria-labelledby="navbarDropdown">
                            <a class="dropdown-item" href="{% url "si_tests:test-list" %}">Список испытаний</a>
                            <a class="dropdown-item" href="{% url "si_tests:test-create" %}">Создать</a>
                            <a class="dropdown-item" href="#">Редактировать</a>
                            <a class="dropdown-item" href="#">Удалить</a>
                            <a class="dropdown-item" href="#">Добавить метод</a>
                            <a class="dropdown-item" href="#">Редактироать метод</a>
                            <a class="dropdown-item" href="#">Удалить метод</a>
                        </div>
                    </li>

                    <li class="nav-item dropdown">
                        <a class="nav-link dropdown-toggle" href="#" id="navbarReport" role="button"
                           data-toggle="dropdown"
                           aria-haspopup="true" aria-expanded="false">
                            Отчеты/выборки
                        </a>

                        <div class="dropdown-menu" aria-labelledby="navbarDropdown">
                            <a class="dropdown-item" href="#">Испытания в работе</a>
                            <a class="dropdown-item" href="#">Ожидают</a>
                            <a class="dropdown-item" href="#">Доработка</a>
                            <a class="dropdown-item" href="#">Завершенные</a>
                        </div>
                    </li>

                    {% if user.is_superuser or user.is_staff %}
                        <li class="nav-item dropdown">
                            <a class="nav-link dropdown-toggle" href="#" id="navbarReport" role="button"
                               data-toggle="dropdown"
                               aria-haspopup="true" aria-expanded="false">Админ панель
                            </a>

                            <div class="dropdown-menu" aria-labelledby="navbarDropdown">
                                <a class="dropdown-item" href="#">Аккредитация пльзователя</a>
                                <a class="dropdown-item" href="#">Действие2</a>
                                <a class="dropdown-item" href="#">Действие3</a>
                                <a class="dropdown-item" href="{% url "admin:index" %}">Админ панель</a>
                            </div>
                        </li>

                    {% endif %}

                    <li class="nav-item">
                        <a class="nav-link disabled" href="#">Disabled</a>
                    </li>
                </ul>

                <div class="inline my-2 my-lg-0">
                    {#                <button class="btn btn-outline-success my-2 my-sm-0" type="submit">Войти b</button>#}
                    {#                <a class="btn btn-outline-success my-2 my-sm-0" href="{% url "si_users:login" %}">Войти а</a>#}
                    <a class="btn btn-outline-success my-2 my-sm-0" href="{% url "si_users:logout" %}">Выйти а</a>
                    {#                <a class="btn button" href="{% url "si_users:registration" %}">Регистрация</a>#}
                </div>


                {#      <li class="nav-item dropdown">#}
                {#        <a class="nav-link dropdown-toggle" href="#" id="navbarDropdown" role="button" data-toggle="dropdown" aria-haspopup="true" aria-expanded="false">#}
                {#          Dropdown#}
                {#        </a>#}
                {#        <div class="dropdown-menu" aria-labelledby="navbarDropdown">#}
                {#          <a class="dropdown-item" href="#">Action</a>#}
                {#          <a class="dropdown-item" href="#">Another action</a>#}
                {#          <div class="dropdown-divider"></div>#}
                {#          <a class="dropdown-item" href="#">Something else here</a>#}
                {#        </div>#}
                {#      </li>#}


                {#    <form class="form-inline my-2 my-lg-0">#}
                {#      <input class="form-control mr-sm-2" type="search" placeholder="Search" aria-label="Search">#}
                {#      <button class="btn btn-outline-success my-2 my-sm-0" type="submit">Search</button>#}
                {#    </form>#}
            </div>

        {% else %}
            <div class="inline my-2 my-lg-0">
                {#                <button class="btn btn-outline-success my-2 my-sm-0" type="submit">Войти b</button>#}
                <a class="btn btn-outline-success my-2 my-sm-0" href="{% url "si_users:login" %}">Войти</a>
                {#            <a class="btn btn-outline-success my-2 my-sm-0" href="{% url "si_users:logout" %}">Выйти а</a>#}
                <a class="btn button" href="{% url "si_users:registration" %}" style="color: #4ac1f7">Регистрация</a>
            </div>
        {% endif %}
    </nav>

{% endblock %}

{% block content %}{% endblock %}

{% block footer %}{% endblock %}
<!-- Optional JavaScript -->
{#<script src="/static/js/htmx.min.js"></script>#}
<script src="{% static 'js/htmx.min.js' %}" defer></script>
{#<script>#}
{#      document.body.addEventListener('htmx:configRequest', (event) => {#}
{#        event.detail.headers['X-CSRFToken'] = '{{ csrf_token }}';#}
{#      })#}
{#</script>#}

{#<!-- jQuery first, then Popper.js, then Bootstrap JS -->#}
<script src="https://code.jquery.com/jquery-3.2.1.slim.min.js"
        integrity="sha384-KJ3o2DKtIkvYIK3UENzmM7KCkRr/rE9/Qpg6aAZGJwFDMVNA/GpGFF93hXpG5KkN"
        crossorigin="anonymous"></script>
<script src="https://cdnjs.cloudflare.com/ajax/libs/popper.js/1.12.9/umd/popper.min.js"
        integrity="sha384-ApNbgh9B+Y1QKtv3Rn7W3mgPxhU9K/ScQsAP7hUibX39j7fakFPskvXusvfa0b4Q"
        crossorigin="anonymous"></script>
<script src="https://maxcdn.bootstrapcdn.com/bootstrap/4.0.0/js/bootstrap.min.js"
        integrity="sha384-JZR6Spejh4U02d8jOt6vLEHfe/JQGiRRSQQxSfFWpi1MquVdAyjUar5+76PVCmYl"
        crossorigin="anonymous"></script>
</body>
</html>

src/si_system/templates/si_system/index.html
{% extends "si_system/base.html" %}
{% load static %}

{% block title %}
    <title>Система контроля тестирования</title>
{% endblock %}

{% block content %}
    <h3>Страница в разработке</h3>
    <img  src="{% static 'img/teh.png' %}">
            
{% endblock %}

{% block footer %}
    <div class="fixed-bottom ">
        <p>Блок футера</p>
    </div>
{% endblock %}