src/enterprise_system/urls.py
from django.contrib import admin
from django.urls import path, include
from django.conf.urls.static import static
from django.conf import settings

from si_system.views import index


urlpatterns = [
    path("devices/", include("si_devices.urls", namespace="si_devices")),
    path("tests/", include("si_tests.urls", namespace="si_tests")),
    path("admin/", admin.site.urls),
    path("users/", include("si_users.urls", namespace="si_users")),
    path("", index, name="index"),
]

# Запуск медиафайлов локально
if settings.DEBUG:
    urlpatterns += static(settings.MEDIA_URL, document_root=settings.MEDIA_ROOT)

src/si_devices/urls.py
from django.urls import path
from django.conf import settings
from django.conf.urls.static import static

from si_devices import views


app_name = 'si_devices'


urlpatterns = [
    path("versions/success/<int:pk>", views.SuccessVersionView.as_view(), name="version-success"),
    path("versions/edit/<int:pk>", views.VersionEditView.as_view(), name="version-edit"),
    path("versions/create", views.VersionCreateView.as_view(), name="version-create"),
    path("versions", views.VersionListView.as_view(), name="version-list"),
    path("<int:pk>/update", views.device_update, name="device-update"),
    path("create", views.DeviceCreateView.as_view(), name="device-create"),
    path("<int:pk>", views.DeviceDetailView.as_view(), name="device-detail"),
    path("", views.DeviceListView.as_view(), name="device-list"),
]


if settings.DEBUG:
    urlpatterns += static(settings.MEDIA_URL, document_root=settings.MEDIA_ROOT)

src/si_tests/urls.py
from django.urls import path
from django.conf import settings
from django.conf.urls.static import static

from si_tests import views


app_name = "si_tests"


urlpatterns = [
    path("<int:pk>/update", views.TestUpdateView.as_view(), name="test-update"),
    path("create", views.TestCreateView.as_view(), name="test-create"),
    path("<int:pk>", views.DetailView.as_view(), name="test-detail"),
    path("", views.TestListView.as_view(), name="test-list"),
]


if settings.DEBUG:
    urlpatterns += static(settings.MEDIA_URL, document_root=settings.MEDIA_ROOT)

src/si_devices/models.py
from django.db import models
from django.utils import timezone


CHOICES_DEVICE_TYPE_RELEASE = (
    ("1", "Серия"),
    ("2", "Опытное"),
    ("3", "Иное"),
)


# переопределение QuerySet для Devices
# class DeviceQuerySet(models.QuerySet):
#     def total_quantity(self):
#         return sum(device for device in self.all())


class Device(models.Model):
    name = models.CharField(max_length=200, verbose_name="Наименование")
    version = models.ForeignKey("Version", on_delete=models.PROTECT, verbose_name="Версия")
    bord = models.CharField(max_length=100, verbose_name="Плата", null=True, blank=True)
    firmware = models.CharField(max_length=50, verbose_name="Прошивка", null=True, blank=True)
    decimal_num = models.CharField(max_length=150, verbose_name="Децимальный номер")
    constructor = models.CharField(max_length=200, verbose_name="Конструктор")
    engineer = models.CharField(max_length=200, verbose_name="Изменил", null=True, blank=True)
    type_release = models.CharField(max_length=50, choices=CHOICES_DEVICE_TYPE_RELEASE, default="1", verbose_name="Вид выпуска")
    date_created = models.DateTimeField(default=timezone.now, verbose_name="Дата создания")
    changed_timestamp = models.DateTimeField(auto_now_add=True, verbose_name="Дата изменения", null=True, blank=True)
    description = models.TextField(verbose_name="Описание", null=True, blank=True)
    image = models.ImageField(verbose_name="Рисунок", upload_to="devices_images", null=True, blank=True)
    # type_device = models.CharField(max_length=250, verbose_name="Тип изделия", null=True, blank=True)

    class Meta:
        verbose_name = "Изделие"
        verbose_name_plural = "Изделия"

    @property
    def full_name(self):
        if self.version.name == "00":
            return f"{self.name} {self.bord}"
        else:
            return f"{self.name} исп.{self.version.name} {self.bord}"

    def __str__(self):
        if self.version.name == "00":
            return f"{self.name}"
        else:
            return f"{self.name} исп.{self.version.name}"


class Version(models.Model):
    name = models.CharField(max_length=10, verbose_name="Версия изделия", unique=True)
    description = models.TextField(verbose_name="Описание", null=True, blank=True)
    date_created = models.DateTimeField(default=timezone.now, verbose_name="Дата создания")
    changed_timestamp = models.DateTimeField(auto_now_add=True, verbose_name="Дата изменения", null=True, blank=True)

    class Meta:
        verbose_name = "Версия"
        verbose_name_plural = "Версии"

    def __str__(self):
        return f"{self.name}"


class Bord(models.Model):
    name = models.CharField(max_length=50, verbose_name="Версия изделия", unique=True)
    description = models.CharField(max_length=250, verbose_name="Описание", null=True, blank=True)
    date_created = models.DateTimeField(default=timezone.now, verbose_name="Дата создания")
    changed_timestamp = models.DateTimeField(auto_now_add=True, verbose_name="Дата изменения", null=True, blank=True)

    class Meta:
        verbose_name = "Версия"
        verbose_name_plural = "Версии"

    def __str__(self):
        return f"{self.name}"

src/si_devices/forms.py
from django import forms
from django.core.exceptions import ValidationError

from si_devices.models import Device, Version, CHOICES_DEVICE_TYPE_RELEASE


class CreateVersionForm(forms.ModelForm):
    class Meta:
        model = Version
        fields = ["name", "description"]
        widgets = {
            "name": forms.TextInput(attrs={"class": "col-lg-1"}),
            "description": forms.TextInput(attrs={"class": "col-lg-4"})
        }

    def clean(self):
        data = self.cleaned_data
        name = self.cleaned_data["name"]

        if Version.objects.filter(name=name):
            raise ValidationError("Такая версия уже есть")
        return data


class DeviceCreateForm(forms.ModelForm):
    decimal_num = forms.CharField(widget=forms.TextInput(), required=False)
    constructor = forms.CharField(widget=forms.TextInput(), required=False)
    description = forms.CharField(widget=forms.TextInput(), required=False)
    image = forms.ImageField(widget=forms.FileInput(), required=False)

    class Meta:
        model = Device
        fields = [
            "name",
            "version",
            "bord",
            "firmware",
            "decimal_num",
            "constructor",
            "type_release",
            "description",
            "image"
        ]


class DeviceEditForm(forms.ModelForm):
    # name = forms.CharField(widget=forms.TextInput(attrs={}),)
    # version = forms.CharField(widget=forms.CharField(choices=Version.name, attrs={}),)
    # bord = forms.CharField(widget=forms.TextInput(),)
    # firmware = forms.CharField(widget=forms.TextInput(),)
    decimal_num = forms.CharField(widget=forms.TextInput(), required=False)
    constructor = forms.CharField(widget=forms.TextInput(), required=False)
    # type_release = forms.CharField(widget=forms.CharField(choices=CHOICES_DEVICE_TYPE_RELEASE,),)
    description = forms.CharField(widget=forms.TextInput(), required=False)
    image = forms.ImageField(widget=forms.FileInput(), required=False)

    class Meta:
        model = Device
        fields = [
            "name",
            "version",
            "bord",
            "firmware",
            "decimal_num",
            "constructor",
            "type_release",
            "description",
            "image"
        ]

src/si_devices/views.py
from contextlib import redirect_stderr
from pickletools import read_long1

from  django.http import HttpResponse
from django.views import generic
from django.urls import reverse_lazy, reverse
from django.http import QueryDict
from django.shortcuts import render, redirect
from django.contrib.auth.decorators import login_required
from django.core.files.storage import FileSystemStorage
from django_htmx.http import HttpResponseClientRedirect

from si_devices.forms import CreateVersionForm, DeviceCreateForm, DeviceEditForm
from si_devices.models import Version, Device

from loguru import logger


class VersionCreateView(generic.CreateView):
    form_class = CreateVersionForm
    model = Version
    context_object_name = "version"
    template_name = "si_devices/version_create.html"

    def get_success_url(self):
        obj = self.object
        return reverse_lazy("si_devices:version-success", kwargs={"pk": obj.id})


class SuccessVersionView(generic.DetailView):
    model = Version
    template_name = "si_devices/version_success.html"


class VersionEditView(generic.UpdateView):
    model = Version
    form_class = CreateVersionForm
    template_name = ""
    context_object_name = "versions"


class VersionListView(generic.ListView):
    model = Version
    context_object_name = "device_versions"
    template_name = "si_devices/versions.html"


    def get_queryset(self):
        context = {}
        context["title"] = "Версии"
        context["versions"] = Version.objects.all()
        return context


class DeviceListView(generic.ListView):
    model = Device
    context_object_name = "context"
    template_name = "si_devices/devices.html"

    def get_queryset(self):
        context = {
            "title": "Список изделий",
            "devices": Device.objects.order_by("name")
        }
        return context


class DeviceDetailView(generic.DetailView):
    model = Device
    context_object_name = "device_info"
    template_name = "si_devices/device_detail.html"

    def get_context_data(self, **kwargs):
        context = super().get_context_data()
        context["device"] = Device.objects.get(pk=self.kwargs["pk"])
        context["title"] = "Информация о изделии:"

        return context

    # def get(self, request, *args, **kwargs):
    #     self.object = self.get_object()
    #     context = self.get_context_data(object=self.object)
    #     logger.info(f"{request.META['HTTP_REFERER']}")
    #     if request.htmx:
    #         logger.info("htmx")
    #         return HttpResponse()
    #     else:
    #         logger.info(f"req  {self.request}")
    #         return self.render_to_response(context)


class DeviceCreateView(generic.CreateView):
    model = Device
    template_name = "si_devices/create_device.html"
    context_object_name = "device"
    form_class = DeviceCreateForm

    def get_success_url(self):
        obj = self.object
        return reverse_lazy("si_devices:device-list")


def device_update(request, pk):
    device = Device.objects.get(id=pk)

    if request.method == "PUT":
        qd = QueryDict(request.body)
        form = DeviceEditForm(instance=device, data=qd)
        if request.htmx:
            if form.is_valid():
                device = form.save()
                context = {"device": device}
                context["device"] = Device.objects.get(pk=device.id)
                context["title"] = "Информация о изделии:"
                return render(request, "si_devices/device_info.html", context)

    form = DeviceEditForm(instance=device)
    context = {
        "form": form,
        "device": device,
        "title": "Обновление"
    }
    return render(request, "si_devices/device_form.html", context)


# def update_view(request, *args, **kwargs):
#     print(kwargs)
#     if request.htmx:
#         logger.info(f"target {request.htmx.target}")
#         print(f"{request.htmx.trigger}")
#
#         if request.method == "POST":
#             ...
#         else:
#             ...
#     else:
#         print(request.content_params())
#         return render(request, "si_devices/device_detail.html", 1)



# class DeviceUpdateView(generic.UpdateView):
#     model = Device
#     form_class = DeviceEditForm
#     # template_name = "si_devices/device_form.html"
#     context_object_name = "device_form"
#
#     def get_context_data(self, **kwargs):
#         context = {"device": Device.objects.get(pk=self.kwargs["pk"])}
#         context["title"] = "Информация о изделии:"
#         return context
#
#     def put(self, request, *args, **kwargs):
#         context = self.get_context_data()
#         return reverse("si_devices:device-update", context)

    # def put(self, *args, **kwargs):




    # def form_valid(self, form):
    #     if self.request.htmx:
    #         logger.info("htmx")
    #     else:
    #         logger.info(f"req  {self.request}")
    #     return reverse("si_devices:device_detail", kwargs={"pk": 1})


    # def dispatch(self, request, *args, **kwargs):
    # template_name_suffix = "si_devices/device_edit"

    # success_url = "si_devices:device_detail"

    # def put(self, *args, **kwargs):
    #     if self.request.htmx:
    #         obj = self.get_object(self.request)
    #         print("htmx", obj.id)
    #         return render(self.request, "si_devices/device_detail.html")
    #     else:
    #         print("not htmx")
    #     return ...

    #     req = self.request.content_params
    #
    #     print(req)
    #     return reverse("si_devices:device_detail", kwargs={"pk":3})

    # def get_success_url(self):
    #     obj = self.object
    #     print(obj)
    #     return reverse("si_devices:device_detail", kwargs={"pk": obj.id})

    # def form_valid(self, form):
    #     print("valid")
    #     return form
    # # def put(self, *args, **kwargs):
    # #     pass
    # def form_invalid(self, form):
    #     print("invalid", not form.errors.items())
    #     return form


# return HttpResponseRedirect(request.META.get('HTTP_REFERER'))

src/si_devices/templates/si_devices/create_device.html
{% extends "si_system/base.html" %}
{% load static %}

{% block title %} Создать изделие {% endblock %}

{% block content %}
<h1>Создать изделие</h1>

{% if error_message %}<p><strong>{{ error_message }}</strong></p>{% endif %}


{#    <form action="{% url 'si_devices:results' device.id %}" method="post">{% csrf_token %}#}
<form method="post" enctype="multipart/form-data">{% csrf_token %}
{#        <p>{{ form.name }}</p>#}

{#        {{ form.non_field_errors }}#}

    {{ form.as_p }}


{#        {{ formset  }}#}

    <input type="submit" value="Создать">

</form>
{% endblock %}

src/si_devices/templates/si_devices/create_version.html
{% extends "si_system/index.html" %}

{% block title %}
    <title>Версия изделия</title>
{% endblock %}

{% block content %}
    <h1>Добавить версию</h1>

    {% if error_message %}
        <p><strong>{{ error_message }}</strong></p>
    {% endif %}

    {% if messages %}
    <ul class="messages">
        {% for message in messages %}
            <li{% if message.tags %} class="{{ message.tags }}"{% endif %}>{{ message }}</li>
        {% endfor %}
    </ul>
    {% endif %}

{#    <a href="{% url 'si_devices:index' %}">Вернутся к списку устройств </a>#}

    <form method="post">{% csrf_token %}
        {{ form.as_p }}

        <input type="submit" value="Создать">
    </form>
{% endblock %}

src/si_devices/templates/si_devices/device_detail.html
{% extends "si_system/index.html" %}
{% load static %}

{% block title %}
    <title>{{ title }}</title>
{% endblock %}

{% block content %}
    <div class="row" style="padding: 50px">
        <div id="device"
            class="col-5" style="background-color: #6f94c6; font-size: 150%"     
            hx-target="this"
            hx-swap="outerHTML"
            >
            <h3>{{ title }} {{ device_info.full_name }} </h3>
            
            <p>{{ device.name }}</p>
            <p>{{ device.get_version_display }}</p>
            <p>{{ device.bord }}</p>
            <p>{{ device.firmware }}</p>
            <p>{{ device.decimal_num }}</p>
            <p>{{ device.constructor }}</p>
            <p>{{ device.get_type_release_display }}</p>
            <p>{{ device.description }}</p>
            
            <button class="btn btn-primary"
                    hx-get="{% url "si_devices:device-update" device.id %}" 
            >Изменить</button>
        </div>
        
        <div id="notepad"
             class="col-7" style="background-color: #f5dd5d"
             hx-target="this"
             hx-swap="outerHTML">
            <h3>Заметки</h3>
            
            <div>
                
            </div>
        </div>
    </div>
    
    <div id="testing"
        class="col-12" style="background-color: powderblue"
        >
        <p>блок тестирования/изменений</p>
    </div>
{% endblock %}



{#{% block content %}#}
{#    <h3>{{ title }} {{ description.full_name }} </h3>#}
{##}
{#    <div class="row">#}
{#        <div class="col-4 " style="background-color: #f5dd5d">#}
{#            блок информации#}
{#            {% block info_device %}#}
{#                <div hx-target="this" #}
{#                     hx-swap="outerHTML">#}
{#                     #}
{#                    <div class="d-flex justify-content-end">#}
                        {#                    <div class="inline my-2 my-lg-0">#}
{#                        <button hx-get="{% url "si_devices:device_edit" description.id %}" class="btn btn-info">#}
{#                            Изменить btn#}
{#                        </button>#}
{#                        <a class="btn btn-info  my-2 my-sm-0" href="#">Изменить</a>#}
                        {#                    </div>#}
{#                    </div>#}
{#                    <table class="table table-info table-striped">#}
{#                        <thead>#}
{#                        <th scope="col">Параметр</th>#}
{#                        <th scope="col">Значение</th>#}
{#                        </thead>#}
{##}
{#                        <tbody>#}
{#                        <tr>#}
{#                            <td class="col-2">Наименование:</td>#}
{#                            <td class="col-3">{{ description.name }}</td>#}
{#                        </tr>#}
{##}
{#                        <tr>#}
{#                            <td>Версия:</td>#}
{#                            <td>{{ description.version }}</td>#}
{#                        </tr>#}
{##}
{#                        <tr>#}
{#                            <td>Плата:</td>#}
{#                            <td>{{ description.bord }}</td>#}
{#                        </tr>#}
{#                        <tr>#}
{#                            <td>Прошивка:</td>#}
{#                            <td>{{ description.firmware }}</td>#}
{#                        </tr>#}
{#                        <tr>#}
{#                            <td>Децимальный номер:</td>#}
{#                            <td>{{ description.decimal_num }}</td>#}
{#                        </tr>#}
{#                        <tr {% if description.get_type_release_display == "Серия" %}#}
{#                            class="table-success" {% elif description.get_type_release_display == "Опытное" %}#}
{#                            class="table-warning" {% endif %}>#}
{#                            <td>Тип выпуска:</td>#}
{#                            <td>{{ description.get_type_release_display }}</td>#}
{#                        </tr>#}
{#                        <tr>#}
{#                            <td>Конструктор:</td>#}
{#                            <td>{{ description.constructor }}</td>#}
{#                        </tr>#}
{#                        <tr>#}
{#                            <td>Описание:</td>#}
{#                            <td>{{ description.description }}</td>#}
{#                        </tr>#}
{#                        </tbody>#}
{#                    </table>#}
{#                </div>#}
{#            {% endblock %}#}
{#        </div>#}
{##}
{#        <div class="col-8" style="background-color: #5b80b2">блок заметок по изделию#}
{#            {% block notebook_device %}#}
{##}
{#            {% endblock %}#}
{#        </div>#}
{#    </div>#}
{##}
{#    <div class="row">#}
{#        {% block testing_device %}#}
{#            <h3 class="col">Испытания</h3>#}
{#            <div class="col-12">Блок испытаний#}
{#            </div>#}
{#        {% endblock %}#}
{#    </div>#}
{#{% endblock %}#}

src/si_devices/templates/si_devices/device_form.html
<div 
     id="device-form"
{#     hx-target="device"#}
     hx-target="#device"   
     hx-swap="outerHTML"
     >
    <h3>Редактирование изделия</h3>
    
    <form> 
        {% csrf_token %}
        {{ form.as_p }}
        
        <button class="btn btn-primary"
            hx-put="{% url "si_devices:device-update" device.id %}"
            type="submit"
            hx-target="#device-form">Send
        </button>
        
        <button class="btn btn-primary">Cancel
        </button>
    </form>
</div>

src/si_devices/templates/si_devices/device_info.html
<div id="device"
    hx-target="this"
    hx-swap="outerHTML">
    <h3>{{ title }} {{ device.full_name }} </h3>
    
    <p>{{ device.name }}</p>
    <p>{{ device.get_version_display }}</p>
    <p>{{ device.bord }}</p>
    <p>{{ device.firmware }}</p>
    <p>{{ device.decimal_num }}</p>
    <p>{{ device.constructor }}</p>
    <p>{{ device.get_type_release_display }}</p>
    <p>{{ device.description }}</p>
    <button class="btn btn-primary"
            hx-get="{% url "si_devices:device-update" device.id %}">Изменить
    </button>
</div>

src/si_devices/templates/si_devices/devices.html
{% extends "si_system/index.html" %}
{% load static %}

{% block title %}
    <title>{{ context.title }}</title>
{% endblock %}

{% block content %}
    <h1>{{ context.title }}</h1>

    <div class="wrapper">
        <table class="table table-bordered table-bordered">
            <thead>
                <th scope="col">Изделие</th>
                <th scope="col">Изделие</th>
                <th scope="col">Версия</th>
                <th scope="col">плата</th>
                <th scope="col">Прошивка</th>
                <th scope="col">Тип выпуска</th>
                <th scope="col">Дец. номер</th>
                <th scope="col">Конструуктор</th>
                <th scope="col">Обновление</th>
            </thead>

            <tbody>
            {% for device in context.devices %}
                <tr>
                    <td>
                        <a href="{% url "si_devices:device-detail" device.id %}"
                           class="list-group-item"> {{ device.full_name }}
                        </a>
                    </td>
                    <td>{{ device.name }}</td>
                    <td>{{ device.version }}</td>
                    <td>{{ device.bord }}</td>
                    <td>{{ device.firmware }}</td>
                    <td {% if device.type_release == 1 %} class="table-success" 
                        {% elif device.type_release == 2 %} class="table-warning"
                        {% else %} class="table-info"                                
                        {% endif %}>
                        {{ device.get_type_release_display }}
                    </td>
                    <td >{{ device.decimal_num }}</td>
                    <td>{{ device.constructor }}</td>
                    <td>{{ device.changed_timestamp }}</td>
                </tr>    
            {% endfor %}
            </tbody>
        </table>
    </div>

{#    {% for device in context.devices %}#}
{#        <div class="list-group">#}
{#            <a href="{% url "si_devices:device_detail" device.id %}"#}
{#               class="list-group-item"> {{ device }} {{ device.get_type_release_display }}#}
{#                {% if device.image %}#}
{#                    <img src="{{ device.image.url }}" alt="">#}
{#                {% endif %}#}
{#            </a>#}
{#        </div>#}
{#    {% endfor %}#}
{% endblock %}

{#вывести рисунок#}
{#<img class="card-img-top"#}
{#     src="{{ class.metod.url }}"#}
{#     alt="">#}
{#{% extends "si_system/base.html" %}#}
{#{% load static %}#}

src/si_devices/templates/si_devices/login.html
{% load static %}

<!DOCTYPE html>
<html lang="en">
    <head>
        <meta charset="UTF-8">

        <link href="sth.css" rel="stylesheet">
        <title>Title</title>
    </head>
    <body>
        <div class="login">
        <h1>Login</h1>
            <form method="post">
                <input type="text" name="u" placeholder="Username" required="required" />
                <input type="password" name="p" placeholder="Password" required="required" />
                <button type="submit" class="btn btn-primary btn-block btn-large">Let me in.</button>
            </form>
        </div>
    </body>
</html>

src/si_devices/templates/si_devices/version_create.html
{% extends "si_system/index.html" %}
{% load static %}

{% block title %}
    <title>Версия изделия</title>
{% endblock %}

{% block content %}
    <h1>Добавить версию</h1>

    {% if error_message %}
        <p><strong>{{ error_message }}</strong></p>
    {% endif %}

    {% if messages %}
    <ul class="messages">
        {% for message in messages %}
            <li{% if message.tags %} class="{{ message.tags }}"{% endif %}>{{ message }}</li>
        {% endfor %}
    </ul>
    {% endif %}

{#    <a href="{% url 'si_devices:index' %}">Вернутся к списку устройств </a>#}

    <form method="post">{% csrf_token %}
        {{ form.as_p }}

        <input type="submit" value="Создать">
    </form>
{% endblock %}

src/si_devices/templates/si_devices/version_success.html
{% extends "si_system/index.html" %}
{% load static %}

{% block title %}
    <title>Версия изделия</title>
{% endblock %}

{% block content %}
    <h3>Версия {{ version.name }} успешно создана</h3>

    {% if messages %}
    <ul class="messages">
        {% for message in messages %}
            <li{% if message.tags %} class="{{ message.tags }}"{% endif %}>{{ message }}</li>
        {% endfor %}
    </ul>
    {% endif %}

{% endblock %}

src/si_devices/templates/si_devices/versions.html
{% extends "si_system/index.html" %}
{% load static %}

{% block title %}
    <title>{{ device_versions.title }}</title>
{% endblock %}

{% block content %}
    <h3>{{ device_versions.title }} изделий.</h3>
    
    {% if device_versions.versions %}
        {% for version in device_versions.versions %}
            <ul>
                <li>{{ version }} | {{ version.name }} | {{ version.description }}</li>
            </ul>
        {% endfor %}
    {% else %}
        <span>Версии не созданы</span>
    {% endif %}
{% endblock %}